version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn
  build:
    commands:
      - echo Executing unit tests
      - yarn build:smithy-client #TODO: change to `yarn test:all` after clients are ready
      - echo Executing functional test
      - yarn test:functional
  post_build:
    commands:
      - ./node_modules/.bin/codecov -f coverage/*.json
